<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net452;net462;net48</TargetFrameworks>
    <OutputType>Library</OutputType>
    <AutoGenerateBindingRedirects>False</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="itextsharp">
      <HintPath>..\Lib\ITextSharp-5.5.2\itextsharp.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
